version: '3'

services:

  #https://openobserve.ai/docs/quickstart/#self-hosted-installation
  #https://gallery.ecr.aws/zinclabs/openobserve
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:v0.4.7
    environment:
      - ZO_ROOT_USER_EMAIL=root@example.com
      - ZO_ROOT_USER_PASSWORD=openobserve
      - ZO_DATA_DIR=/data
    volumes:
      - openobservedata:/data
    ports:
      - 5080:5080

  prometheus:
    depends_on:
      - openobserve
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./dev/docker/prometheus:/etc/prometheus
    command: "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: always

  docker-exporter:
    image: prometheusnet/docker_exporter:latest
    container_name: docker_exporter
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9417:9417

volumes:
  openobservedata:
    driver: local