logging:
  level:
    '[io.micrometer.tracing]': trace
    '[io.opentelemetry.exporter.zipkin]': trace
    '[zipkin2]': trace

server:
  tomcat:
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

  tracing:
    enabled: true
    propagation: 
      type: b3
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      connect-timeout: 2s
      read-timeout: 5s
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: @project.name@

app:
  backend-url: http://localhost:8081/