logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}-%X{spanId}] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

  tracing:
    enabled: true
    propagation:
      type: b3
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      connect-timeout: 2s
      read-timeout: 5s
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: @project.name@
