logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}-%X{spanId}] %-5level %logger{36} - %msg%n"

server:
  port: 8081
  tomcat:
    accesslog:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

  tracing:
    enabled: true
    propagation:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:8200/v1/traces
    metrics:
      export:
        enabled: true
        url: http://localhost:8200/v1/metrics
        resource-attributes:
          '[service.name]': "@project.name@"

spring:
  application:
    name: @project.name@