global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'micrometer-prometheus'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
        - host.docker.internal:8080
        - host.docker.internal:8081

  - job_name: 'docker-metric'
    static_configs:
      - targets:
        - docker-exporter:9417

remote_write:
  - url: http://openobserve:5080/api/default/prometheus/api/v1/write
    basic_auth:
      username: root@example.com
      password: KCvU1y3hYCav63yv
